#!/bin/bash

source "$HOME/lab/pipex/tester/scripts/tester_utils"

check_memory_leaks() {
    local cmd1=$1
    local cmd2=$2

    local valgrind_log=$(mktemp)
    valgrind --leak-check=full $PIPEX infile "$cmd1" "$cmd2" outfile &> "$valgrind_log"

    if grep -q "in use at exit: 0 bytes in 0 blocks" "$valgrind_log"; then
        leaks_status="${GREEN}[OK]${NC}"
    else
        leaks_status="${RED}[KO]${NC}"
    fi

    rm -f "$valgrind_log"
}

run_test() {
    local desc=$1
    local content=$2
    local cmd1=$3
    local cmd2=$4

    reset_files "$content"
    setup_expected_output "$cmd1" "$cmd2"
    local expected=$(cat expected_outfile)
    $PIPEX infile "$cmd1" "$cmd2" outfile
    local result=$(cat outfile 2>/dev/null)
    compare_results "$expected" "$result"
    check_memory_leaks "$cmd1" "$cmd2"
    print_test_result "$desc" "$expected" "$result"
}
