#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
WHITE='\033[1;37m'
NC='\033[0m'

PIPEX="$HOME/lab/pipex/pipex/pipex"


print_header() {
    printf "\n${CYAN}═══════════════════════════════════════════════════════════════════════════════${NC}\n"
    printf "${WHITE} %-52s %-10s %-10s ${NC}\n" "Test" "Result" "Leaks"
    printf "${CYAN}═══════════════════════════════════════════════════════════════════════════════${NC}\n"
}

reset_files() {
    rm -f infile outfile expected_outfile
    echo -e "$1" > infile
}

print_final() {
	printf "\n${CYAN}═══════════════════════════════════════════════════════════════════════════════${NC}\n"
	printf "${GREEN}All tests completed.${NC}\n"
	printf "${CYAN}═══════════════════════════════════════════════════════════════════════════════${NC}\n\n"
}
